// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Content: typeof import('./components/Content.vue')['default']
    MyTransition: typeof import('./components/MyTransition.vue')['default']
    NormalContent: typeof import('./components/NormalContent.vue')['default']
    OuterFrame: typeof import('./components/OuterFrame.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
